security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      # auth-server in case of docker deployment
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: BUGFIX   

spring:
  data:
    mongodb:
      host: localhost
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: eventdriven_account
      port: 27017
  main:
    allow-bean-definition-overriding: true
    
server:
  servlet:
    context-path: /accounts
  port: 6000



