version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: eventdriven_auth
      MONGODB_USER: oauth-user
      MONGODB_DATABASE: eventdriven_auth
      MONGODB_PASS: password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"  
    volumes:
      - ./mongo_data/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
#      - mongodata:/data/db
    ports:
      - 27017:27017
      
  mongo-express-oauth:
    image: mongo-express:0.49
    restart: always
    ports:
      - 10081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongodb   