security:
  oauth2:
    client:
      clientId: account-service
#      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      clientSecret: 1234
      # auth-server in case of docker deployment of the service
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: BUGFIX
         
spring:
  cloud:
    stream:
      default-binder: kafka
      bindings:
        accountcreateoutput:
           group: output-group-1
           destination: accountcreated
           producer:
             header-mode: headers
      kafka:
        binder:
          brokers: localhost:5050
          configuration:
            commit:
              interval:
                 mms: 1000  
            default:
              key:
                serde: org.apache.kafka.common.serialization.Serdes$StringSerde  
              value:
                serde: org.apache.kafka.common.serialization.Serdes$StringSerde  
  data:
    mongodb:
      host: localhost
      username: oauth-user
      password: password
      database: eventdriven_account
      port: 27017
  
    
server:
  servlet:
    context-path: /accounts
  port: 6000
