spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: oauth-user
      password: password
      database: eventdriven_auth

server:
  servlet:
     context-path: /uaa
  port: 5000
  
eureka:
  client:
    fetchRegistry: true